config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  root 'welcome#index'

  get 'assignment/:id' => 'assignment#show'
  post "login" => "sessions#create", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :teacher
  resources :message
  resources :assignment
  resources :assignment_student

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	belongs_to :teacher
	belongs_to :assignment_type
	has_many :assignment_comments
	has_many :assignment_versions

	has_many :assignment_students
	has_many :students,  through: :assignment_students
end

app/models/assignment_comment.rb
class AssignmentComment < ActiveRecord::Base
	belongs_to :assignment
end

app/models/assignment_student.rb
class AssignmentStudent < ActiveRecord::Base
	belongs_to :assignment 
	belongs_to :student 
end

app/models/assignment_type.rb
class AssignmentType < ActiveRecord::Base
	has_many :assignments
end

app/models/assignment_version.rb
class AssignmentVersion < ActiveRecord::Base
	belongs_to :assignment
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_secure_password

	has_many :assignment_students
	has_many :assignments, through: :assignment_students
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	has_secure_password

	has_many :assignments
	

	validates :password, presence: true, on: :create
	  
	validates :email,
			  :presence => true,
              :uniqueness => true,
              :format => { :with => /.+@.+\..+/ }

end

app/controllers/message_controller.rb
class MessageController < ApplicationController
	def index
		@messages = Message.all
	end

	def create
		@message = Message.create(message_params)		
		@assignment = Assignment.find(@message.assignment_id)
		redirect_to assignment_path(@assignment)
	end

	private

	def message_params
    params.require(:message).permit(:content, :assignment_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
  	reset_session
  	@teacher = Teacher.find_by_email(teacher_params[:email])
		if @teacher && @teacher.authenticate(teacher_params[:password])
			new_session
			redirect_to teacher_path(@teacher)
		else
			flash.notice = 'Incorrect username or password.'
  		redirect_to root_path
		end
  end

  def destroy
    end_session
    flash.notice = "Successfully logged out."
    redirect_to root_path
  end


private 

	def teacher_params
    params.require(:teacher).permit(:email, :password)
  end
	
	def new_session
    session[:teacher_id] = @teacher.id
  end

  def end_session
    session.clear
  end  

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController

  def index
  end

  def show
    current_teacher
    @assignments = Assignment.all
    @type = AssignmentType.first
  end

  def new
    @teacher = Teacher.new
  end

  def edit
  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      flash.notice = "User was successfully created."
      redirect_to root_path
    else
      flash.notice = "Try again."
      render :new
    end
  end

  def update
    if current_teacher.update(teacher_params)
      flash.notice = 'User was successfully updated.'
      redirect_to teacher_path(@teacher)
    else
      flash.notice = "Try again."
      render :edit
    end
  end

  # def destroy
  #   @user.destroy
  #   flash.notice = 'User was successfully destroyed.'
  #   redirect_to root_path
  # end

private

  def teacher_params
    params.require(:teacher).permit(:prefix, :name, :email, :password)
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def index
  end

  def show
    current_teacher
  end

  def new
    @teacher = Teacher.new
  end

  def edit
  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      flash.notice = "User was successfully created."
      redirect_to root_path
    else
      flash.notice = "Try again."
      render :new
    end
  end

  def update
    if current_teacher.update(teacher_params)
      flash.notice = 'User was successfully updated.'
      redirect_to teacher_path(@teacher)
    else
      flash.notice = "Try again."
      render :edit
    end
  end

  # def destroy
  #   @user.destroy
  #   flash.notice = 'User was successfully destroyed.'
  #   redirect_to root_path
  # end

private

  def teacher_params
    params.require(:teacher).permit(:email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pairs</title>
  <link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>

    <nav>
    <div class="fixed">
    <nav class="top-bar">
      <div class="left">
        <%= link_to root_path do %>
          <%= image_tag("pairs-small.png") %>
        <% end %>
      </div>
      <div class="right">
        <ul>
        <% if logged_in? %>
            <div class="loggedin">
              <div class="small-7 columns signup">
              
              <div class="small-2 columns">
                <%= link_to "Profile", current_teacher %>
              </div>
              <div class="small-2 columns">
                <%= link_to "Logout", logout_path %>
              </div>
            </div>
        <% else %>
            <%= form_for(:teacher, :url => {:controller => 'sessions', :action => 'create'}) do |f| %>
              <div class="small-3 columns">
                <%= link_to "Sign Up", new_teacher_path, :class => "signup" %>
              </div>
              <div class="small-4 columns">
                <%= f.email_field :email, :autofocus => true,:value => nil, placeholder: 'email' %>
              </div>
              <div class="small-4 columns">
                <%= f.password_field :password, :autofocus => true, placeholder: 'password' %>
              </div>
              <div class="small-1 columns">
                <%= f.submit 'Sign In' %>
              </div>
            <% end %>
        <% end %>
        </ul>
      </div>
    </nav>
    </div>
  </header>

	<p class="flash"><%= flash.notice %></p>
	<%= yield %>

</body>
</html>